"Debianize LXD":
  tags: [lxd]
  variables:
    LXD_VERSION: '5.9'
  image: images:ubuntu/20.04
  before_script:
    # setup golang
    - curl -OL https://go.dev/dl/go1.19.4.linux-amd64.tar.gz
    - tar -C /usr/local -xzf go1.19.4.linux-amd64.tar.gz
    # setup build deps
    - apt update
    - apt install --yes
        acl
        attr
        autoconf
        automake
        dnsmasq-base
        git
        libacl1-dev
        libcap-dev
        liblxc1
        liblxc-dev
        libsqlite3-dev
        libtool
        libudev-dev
        liblz4-dev
        libuv1-dev
        make
        pkg-config
        rsync
        squashfs-tools
        tar
        tcl
        xz-utils
        ebtables
        devscripts
        debhelper
  script:
    # download upstream release
    - export PATH="/usr/local/go/bin:$PATH"
    - curl -OL https://github.com/lxc/lxd/releases/download/lxd-${LXD_VERSION}/lxd-${LXD_VERSION}.tar.gz
    - tar xf lxd-${LXD_VERSION}.tar.gz

    # build upstream release
    - cd lxd-${LXD_VERSION}

    - go mod tidy
    - make deps

    - export CGO_CFLAGS="-I$(pwd)/vendor/raft/include/ -I$(pwd)/vendor/dqlite/include/"
    - export CGO_LDFLAGS="-L$(pwd)/vendor/raft/.libs -L$(pwd)/vendor/dqlite/.libs/"
    - export LD_LIBRARY_PATH="$(pwd)/vendor/raft/.libs/:$(pwd)/vendor/dqlite/.libs/"
    - export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"
    - make

    # copy release artifacts
    - mkdir -p ../pkgdata/lxd/usr/bin/
    - mkdir -p ../pkgdata/lxd/usr/lib/

    - cp $(go env GOPATH)/bin/lxd ../pkgdata/lxd/usr/bin/
    - cp $(go env GOPATH)/bin/lxd-user ../pkgdata/lxd/usr/bin/
    - cp $(go env GOPATH)/bin/lxc ../pkgdata/lxd/usr/bin/

    - cp --preserve=links $(pwd)/vendor/dqlite/.libs/*.so ../pkgdata/lxd/usr/lib/
    - cp --preserve=links $(pwd)/vendor/raft/.libs/*.so ../pkgdata/lxd/usr/lib/

    - cd ..
    - debuild -us -uc
    - mv ../*.deb .
    - mv ../*.changes .
    - mv ../*.buildinfo .
  artifacts:
    paths:
      - '*.deb'
      - '*.changes'
      - '*.buildinfo'
